package com.graphhopper.routing.util.probabilistic;

public enum GridEntryValueType
{
    WEATHER_ATMOSPHERE_HUMIDITY,
    WEATHER_ATMOSPHERE_PRESSURE,
    WEATHER_CLOUDAGE,
    WEATHER_MAXIMUM_WIND_SPEED,
    WEATHER_PRECIPITATION_DEPTH,
    WEATHER_SNOW_HEIGHT,
    WEATHER_SUNSHINE_DURATION,
    WEATHER_TEMPERATURE,
    WEATHER_TEMPERATURE_HIGH,
    WEATHER_TEMPERATURE_LOW,
    WEATHER_WINDCHILL,
    WEATHER_WIND_SPEED
}
